# syntax=docker/dockerfile:1
ARG BUILDPLATFORM
ARG TARGETOS=linux
ARG TARGETARCH=amd64
FROM --platform=$BUILDPLATFORM golang:1.25-alpine AS builder
WORKDIR /src

COPY go.work go.work.sum* ./
COPY go.mod go.sum ./
COPY internal/ ./internal/

COPY apps/fhir-bridge/go.mod apps/fhir-bridge/go.sum ./apps/fhir-bridge/

RUN --mount=type=cache,target=/go/pkg/mod \
    cd apps/fhir-bridge && go mod download

COPY apps/fhir-bridge/ ./apps/fhir-bridge/

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath -o /bin/fhir-bridge ./apps/fhir-bridge/...

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /bin/fhir-bridge /fhir-bridge
EXPOSE 8080
ENTRYPOINT ["/fhir-bridge"]
