# syntax=docker/dockerfile:1
ARG BUILDPLATFORM
ARG TARGETOS=linux
ARG TARGETARCH=amd64
FROM --platform=$BUILDPLATFORM golang:1.25-alpine AS builder
ENV GOWORK=off
WORKDIR /src

COPY go.mod go.sum ./
COPY internal/ ./internal/

COPY apps/notification-service/go.mod apps/notification-service/go.sum ./apps/notification-service/

RUN --mount=type=cache,target=/go/pkg/mod \
    cd apps/notification-service && go mod download

COPY apps/notification-service/ ./apps/notification-service/

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath -o /bin/notification-service ./apps/notification-service/...

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /bin/notification-service /notification-service
EXPOSE 8080
ENTRYPOINT ["/notification-service"]
