server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /events/ {
        proxy_pass http://gateway:8080;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
    }

    location /admissions  { proxy_pass http://gateway:8080; }
    location /discharges  { proxy_pass http://gateway:8080; }
    location /transfers   { proxy_pass http://gateway:8080; }
    location /alerts      { proxy_pass http://gateway:8080; }
    location /lab-results { proxy_pass http://gateway:8080; }
    location /simulator   { proxy_pass http://gateway:8080; }
    location /chaos       { proxy_pass http://gateway:8080; }
    location /metrics     { proxy_pass http://gateway:8080; }

    location /audit       { proxy_pass http://audit-service:8081; }
    location /dlq         { proxy_pass http://audit-service:8081; }
}
